# Generated by Django 5.1.3 on 2024-11-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Я соглашаюсь на обработку моих персональных данных'),
        ),
    ]
