# Generated by Django 5.1.3 on 2024-11-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0002_alter_customuser_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=128, null=True, verbose_name='Повтор пароля'),
        ),
    ]
