# Generated by Django 5.1.3 on 2024-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0002_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(null=True, upload_to='designs/'),
        ),
    ]
