# Generated by Django 5.1.3 on 2024-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0003_customuser_alter_designsuggestion_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
